pin click version <8.2 for OSS CI
Summary:
Example type-check workflow failure: https://github.com/meta-pytorch/captum/actions/runs/22370953193/job/64749427532?pr=1793
```
Collecting click>=8.2.1 (from typer>=0.24.0->typer-slim->transformers)
[...]
pyre-check-nightly 0.0.101750936314 requires click<8.2.0,>=8.0, but you have click 8.3.1 which is incompatible.
[...]
+ pyre check

25lUsage: pyre [OPTIONS] COMMAND [ARGS]...
Try 'pyre -h' for help.

Error: Invalid value for '--version': <VersionKind.NONE: 'none'> is not one of 'none', 'client', 'client_and_binary'.
```

See https://github.com/facebook/pyre-check/issues/988

Reviewed By: craymichael

Differential Revision: D94275432

fbshipit-source-id: d445c9f3fae0bcea1748cb7618b9b31e7edb00f8